/*
 * This file is generated by jOOQ.
 */
package org.aeros.tasks.jooq;


import java.util.Arrays;
import java.util.List;

import org.aeros.tasks.jooq.tables.Lists;
import org.aeros.tasks.jooq.tables.SchemaVersion;
import org.aeros.tasks.jooq.tables.Tasks;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.lists</code>.
     */
    public final Lists LISTS = Lists.LISTS;

    /**
     * The table <code>public.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>public.tasks</code>.
     */
    public final Tasks TASKS = Tasks.TASKS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.LIST_ID_SEQ,
            Sequences.TASK_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Lists.LISTS,
            SchemaVersion.SCHEMA_VERSION,
            Tasks.TASKS
        );
    }
}
