/*
 * This file is generated by jOOQ.
 */
package org.aeros.tasks.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.list_id_seq</code>
     */
    public static final Sequence<Long> LIST_ID_SEQ = Internal.createSequence("list_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, 3, null, null, false, null);

    /**
     * The sequence <code>public.task_id_seq</code>
     */
    public static final Sequence<Long> TASK_ID_SEQ = Internal.createSequence("task_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, 3, null, null, false, null);
}
