/*
 * This file is generated by jOOQ.
 */
package org.aeros.tasks.jooq;


<<<<<<< HEAD:tasks/src/main/jooq/org/aeros/tasks/jooq/Tables.java
=======
import org.aeros.tasks.jooq.tables.FlywaySchemaHistory;
>>>>>>> c66c6e381fc3f7a5ab8e5e27bb3239201cefe13a:rhine/src/main/jooq/com/redstorm/rhine/jooq/Tables.java
import org.aeros.tasks.jooq.tables.Lists;
import org.aeros.tasks.jooq.tables.SchemaVersion;
import org.aeros.tasks.jooq.tables.Tasks;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.lists</code>.
     */
    public static final Lists LISTS = Lists.LISTS;

    /**
     * The table <code>public.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>public.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;
}
