/*
 * This file is generated by jOOQ.
 */
package org.aeros.tasks.jooq;


import org.aeros.tasks.jooq.tables.FlywaySchemaHistory;
import org.aeros.tasks.jooq.tables.Lists;
import org.aeros.tasks.jooq.tables.SchemaVersion;
import org.aeros.tasks.jooq.tables.Tasks;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.lists</code>.
     */
    public static final Lists LISTS = Lists.LISTS;

    /**
     * The table <code>public.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>public.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;
}
