/*
 * This file is generated by jOOQ.
 */
package com.redstorm.rhine.jooq;


import com.redstorm.rhine.jooq.tables.Lists;
import com.redstorm.rhine.jooq.tables.SchemaVersion;
import com.redstorm.rhine.jooq.tables.Tasks;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.lists</code>.
     */
    public static final Lists LISTS = Lists.LISTS;

    /**
     * The table <code>public.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>public.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;
}
